### PR TITLE
Iteration3 UI directional arrows

### PR DESCRIPTION
**Pull request by chrisdemaio**
This includes the creation of directional arrows for the user to follow as they progress through edges and nodes. It also includes some debugging for the textual directions themselves (I think I fixed the problem where it stopped too soon).

### CODE REVIEW

**Comment by nyoma-diamond** [comment]
On hold for debugging

**Comment by chrisdemaio** [comment]
De bugs have been debugged

**Comment by nyoma-diamond** [comment]
more debugging necessary

**Comment by chrisdemaio** [comment]
Let's try this again

**Pull request merged**
